#
# Macro file for the initialization phase of "moller_sim.cc"
# when runing in interactive mode
#

# create empty scene
/vis/open OGLSX  600x400

#
# Create a scene handler for a specific graphics system
# (Edit the next line(s) to choose another graphic system)
#

/vis/drawVolume
/vis/viewer/set/style s
/control/execute viewangle.mac

/vis/scene/add/trajectories smooth rich

# don't plot gammas
/vis/filtering/trajectories/create/particleFilter
/vis/filtering/trajectories/particleFilter-0/add gamma
/vis/filtering/trajectories/particleFilter-0/invert true

# only plot negative particles
/vis/filtering/trajectories/create/chargeFilter
/vis/filtering/trajectories/chargeFilter-0/add -1

# in the energy range of interest
/vis/filtering/trajectories/create/attributeFilter
/vis/filtering/trajectories/attributeFilter-0/setAttribute IMag
/vis/filtering/trajectories/attributeFilter-0/addInterval 2.5 GeV 11 GeV

/vis/scene/add/trajectories smooth rich

# (if you prefer refreshing each event, comment out next line)
/vis/scene/endOfEventAction accumulate

/vis/viewer/set/hiddenMarker true

