#/moller/ana/rootfilename test_septum_sensitive_prexI
#/moller/ana/rootfilename test_prexII_collimator_design2
#/moller/ana/rootfilename prexII_std_coll
#/moller/ana/rootfilename prexII_test_coll_1
#/moller/ana/rootfilename prexII_test_coll_2
#/moller/ana/rootfilename prexII_test_coll_1_shielding
#/moller/ana/rootfilename prexII_test_coll_2_shielding
#/moller/ana/rootfilename prexII_std_coll_shielding
#/moller/ana/rootfilename prexII_target_only
#/moller/ana/rootfilename /home/rakithab/Simulation_Analysis/Geant4/PREX/rootfiles/prexII_std_coll_setup
#/moller/ana/rootfilename /home/rakithab/Simulation_Analysis/Geant4/PREX/rootfiles/prexII_std_coll_setup_no_shield
#/moller/ana/rootfilename /home/rakithab/Simulation_Analysis/Geant4/PREX/rootfiles/test_tmp
#/moller/ana/rootfilename /home/rakithab/Simulation_Analysis/Geant4/PREX/rootfiles/prexII_tgt_only_scan_6
#/moller/ana/rootfilename /home/rakithab/Simulation_Analysis/Geant4/PREX/rootfiles/prexII_tgt_only_cw70_scan
#/moller/ana/rootfilename /home/rakithab/Simulation_Analysis/Geant4/PREX/rootfiles/prexII_tgt_only_w_scan
#/moller/ana/rootfilename /home/rakithab/Simulation_Analysis/Geant4/PREX/rootfiles/prexII_coll_prototype_1
#/moller/ana/rootfilename /home/rakithab/Simulation_Analysis/Geant4/PREX/rootfiles/prexII_coll_prototype_2
#/moller/ana/rootfilename /home/rakithab/Simulation_Analysis/Geant4/PREX/rootfiles/prexII_coll_prototype_3_cone_scan_2
#/moller/ana/rootfilename /home/rakithab/Simulation_Analysis/Geant4/PREX/rootfiles/prexII_coll_prototype_3_new_bore
#/moller/ana/rootfilename /home/rakithab/Simulation_Analysis/Geant4/PREX/rootfiles/prexII_coll_prototype_4
#/moller/ana/rootfilename /home/rakithab/Simulation_Analysis/Geant4/PREX/rootfiles/prexII_coll_prototype_4_square
#/moller/ana/rootfilename /home/rakithab/Simulation_Analysis/Geant4/PREX/rootfiles/prexII_coll_new_length_scan_6_xy_offset
#/moller/ana/rootfilename /home/rakithab/Simulation_Analysis/Geant4/PREX/rootfiles/prexII_coll_prototype_3_septum_p_beam_pipe
#/moller/ana/rootfilename /home/rakithab/Simulation_Analysis/Geant4/PREX/rootfiles/prexII_coll_prototype_3_septum_p_beam_pipe_real_raster
#/moller/ana/rootfilename /home/rakithab/Simulation_Analysis/Geant4/PREX/rootfiles/prexII_coll_prototype_3_septum_p_beam_pipe_no_raster
#/moller/ana/rootfilename /home/rakithab/Simulation_Analysis/Geant4/PREX/rootfiles/prexII_coll_prototype_3_w_beamline
#/moller/ana/rootfilename /home/rakithab/Simulation_Analysis/Geant4/PREX/rootfiles/prexII_tgt_only_raster_check_no_target
#/moller/ana/rootfilename /home/rakithab/Simulation_Analysis/Geant4/PREX/rootfiles/prexII_tgt_only_parallel_raster_check_w_target
#/moller/ana/rootfilename /home/rakithab/Simulation_Analysis/Geant4/PREX/rootfiles/prexII_tgt_only_no_raster_check_w_target
#/moller/ana/rootfilename /home/rakithab/Simulation_Analysis/Geant4/PREX/rootfiles/prexII_coll_prototype_4_septum_p_beam_pipe

#/moller/ana/rootfilename /home/rakithab/Simulation_Analysis/Geant4/PREX/rootfiles/prexII_coll_prototype_4_septum_p_beam_pipe_bore_scan_1
#/moller/ana/rootfilename /home/rakithab/Simulation_Analysis/Geant4/PREX/rootfiles/prexII_coll_prototype_4_bore_scan_4
#/moller/ana/rootfilename /home/rakithab/Simulation_Analysis/Geant4/PREX/rootfiles/prexII_coll_prototype_4_all_w
#/moller/ana/rootfilename /home/rakithab/Simulation_Analysis/Geant4/PREX/rootfiles/prexII_with_prexI_coll_no_shield
#/moller/ana/rootfilename /home/rakithab/Simulation_Analysis/Geant4/PREX/rootfiles/prexII_coll_length_scan_7
#/moller/ana/rootfilename /home/rakithab/Simulation_Analysis/Geant4/PREX/rootfiles/prexII_target_only_rad_scan_3
#/moller/ana/rootfilename /home/rakithab/Simulation_Analysis/Geant4/PREX/rootfiles/prexI_std_coll_septum_p_beam_pipe
#/moller/ana/rootfilename /home/rakithab/Simulation_Analysis/Geant4/PREX/rootfiles/prexI_std_coll
#
#/moller/ana/rootfilename /home/rakithab/Simulation_Analysis/Geant4/PREX/rootfiles/prexII_coll_pt_4_elechut
#/moller/ana/rootfilename /home/rakithab/Simulation_Analysis/Geant4/PREX/rootfiles/prexI_std_coll_elechut
#/moller/ana/rootfilename /home/rakithab/Simulation_Analysis/Geant4/PREX/rootfiles/prexII_coll_pt_4_krypto_elechut
#/moller/ana/rootfilename /home/rakithab/Simulation_Analysis/Geant4/PREX/rootfiles/prexI_std_coll_krypto_elechut
#/moller/ana/rootfilename /home/rakithab/Simulation_Analysis/Geant4/PREX/rootfiles/prexII_coll_pt_4_krypto_scat
#/moller/ana/rootfilename /home/rakithab/Simulation_Analysis/Geant4/PREX/rootfiles/prexII_coll_pt_4_complete
#/moller/ana/rootfilename /home/rakithab/Simulation_Analysis/Geant4/PREX/rootfiles/prexII_coll_pt_4_complete_w_fringe_field_extnd
#/moller/ana/rootfilename /home/rakithab/Simulation_Analysis/Geant4/PREX/rootfiles/prexII_coll_pt_4_complete_w_beamline
#/moller/ana/rootfilename /home/rakithab/Simulation_Analysis/Geant4/PREX/rootfiles/prexII_coll_pt_4_complete_no_shield
#/moller/ana/rootfilename /home/rakithab/Simulation_Analysis/Geant4/PREX/rootfiles/prexII_coll_pt_4_complete_new_shield
/moller/ana/rootfilename /home/rakithab/Simulation_Analysis/Geant4/PREX/rootfiles/prexII_coll_pt_4_complete_new_water_shield_1
#/moller/ana/rootfilename /home/rakithab/Simulation_Analysis/Geant4/PREX/rootfiles/prexII_coll_pt_4_complete_new_shield_Cu_abs
#/moller/ana/rootfilename /home/rakithab/Simulation_Analysis/Geant4/PREX/rootfiles/prexII_coll_pt_4_complete_w_fringe_field_extnd_30cm.root
#/moller/ana/rootfilename /home/rakithab/Simulation_Analysis/Geant4/PREX/rootfiles/prexII_new_shield_limited_scan_5
#/moller/ana/rootfilename /home/rakithab/Simulation_Analysis/Geant4/PREX/rootfiles/prexII_new_shield_check
#/moller/ana/rootfilename /home/rakithab/Simulation_Analysis/Geant4/PREX/rootfiles/prexI_std_coll_complete
#/moller/ana/rootfilename /home/rakithab/Simulation_Analysis/Geant4/PREX/rootfiles/prexI_std_coll_complete_w_beamline
/gun/particle e-
/gun/energy 1.05 GeV
#5 by 5 mm raster
/moller/gun/gen 7
#10 million
#/run/beamOn 10000000

# 1 million
#/run/beamOn 1000000
# 2 million
/run/beamOn 1000000

#/run/beamOn 500000
#/run/beamOn 1000
