/control/macroPath macros
/control/verbose 2
/run/verbose 0
/tracking/verbose 0
/moller/gun/setConstSeed true ##FIXME later
/moller/det/readGeometryFromFile true
/gun/particle e-
/moller/gun/gen 7
/random/setSeeds 123515 9816459

############
### PREX II configurations
############
#### beam energy
/gun/energy 1.05 GeV ##PREX
#/gun/energy 2.2 GeV ##CREX
#### Set B field configuration (prex1, prex2, crex)
/moller/field/setConfiguration prex2
/moller/field/useQ1fringeField true
#### Geometry files
#/moller/det/setDetectorFileName geometry/kriptoniteDetectors_withHRS.gdml
#/moller/det/setDetectorFileName geometry/subTargetChamber.gdml
#/moller/det/setDetectorFileName geometry/subCollShields.gdml
#/moller/det/setDetectorFileName geometry/subBeamPipe.gdml
#/moller/det/setDetectorFileName geometry/subExtendedDump.gdml
#/moller/det/setDetectorFileName geometry/subSkyshineIronV3.gdml
#/moller/det/setDetectorFileName geometry/subHallLid.gdml
#/moller/det/setDetectorFileName geometry/subCollimator.gdml
#/moller/det/setDetectorFileName geometry/subBeamPipe_newSAMs.gdml
#/moller/det/setDetectorFileName geometry/prexII_v2geom.gdml
#/moller/det/setDetectorFileName geometry/prexII_v2SAMs.gdml
#/moller/det/setDetectorFileName geometry/prexII_v2Point6degSAMs.gdml
#/moller/det/setDetectorFileName geometry/prexII_v1ThickConcSS.gdml
#/moller/det/setDetectorFileName geometry/subBeamPipe_newSAMsAlFlange.gdml
#/moller/det/setDetectorFileName geometry/crex5_v1ThickConcSS.gdml
#/moller/det/setDetectorFileName geometry/prexII_v2NewSAMsAlFlange.gdml
#/moller/det/setDetectorFileName geometry/tritium_v1.gdml
#/moller/det/setDetectorFileName geometry/subTritiumTarget.gdml
#/moller/det/setDetectorFileName geometry/subSkyshine.gdml
#/moller/det/setDetectorFileName geometry/subBeamPipe_newSAMsDoubleRing.gdml
#/moller/det/setDetectorFileName geometry/pvdis.xml
#/moller/det/setDetectorFileName geometry/kriptoniteDetectors_tritium.gdml
/moller/det/setDetectorFileName geometry/prexII_v3usTgt.gdml
#/moller/det/setDetectorFileName geometry/crex_v3NewTargPos.gdml
#/moller/det/setDetectorFileName geometry/subCollShieldBlock.gdml

/moller/det/setShieldMaterial polyethylene
/testhadr/CutsAll          0.7 mm
/run/initialize
